### Optional: Default log level
global_level = 'info'
### Optional: specify a regular expression to suppress all messages that don't match
#global_pattern = 'foo'

### Specific log levels per module are optionally defined in this section
[modules]
'cmemu_lib::engine' = 'debug'
'cmemu_lib::component::core' = 'trace'
'cmemu_lib::clock' = 'debug'
