### Optional: Default log level
global_level = 'info'

### Optional: specify a regular expression to suppress all messages that don't match
#global_pattern = 'foo'

### Specific log levels per module are optionally defined in this section
[modules]
'cmemu_lib::component::clock_tree::nodes' = 'trace'
'cmemu_lib::component::clock_tree' = 'debug'
'cmemu_lib::component::core' = 'info'
'cmemu_lib::component::nvic' = 'trace'
'cmemu_lib::component::prcm' = 'trace'
'cmemu_lib::component::rtc' = 'trace'
'cmemu_lib::component::aon' = 'debug'
# Because the above is a prefix...
'cmemu_lib::component::rtc_bypass' = 'info'
'cmemu_lib::clock' = 'debug'
#'cmemu_lib::proxy' = 'debug'
